# repos:
# 	- repo: https://github.com/pre-commit/pre-commit-hooks
# 		rev: v4.5.0
# 		hooks:
# 		- id: check-merge-conflict
# 		- id: check-added-large-files
# 		- id: detect-private-key
# 		- id: check-yaml
# 		- id: check-case-conflict
# 		- id: mixed-line-ending

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-case-conflict
